//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Photo_GalleryEntities6 : DbContext
    {
        public Photo_GalleryEntities6()
            : base("name=Photo_GalleryEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GALLERY_LIST> GALLERY_LIST { get; set; }
        public virtual DbSet<PICTURE_LIST> PICTURE_LIST { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
