//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PICTURE_LIST
    {
        public int ID { get; set; }
        public int Gallery_ID { get; set; }
        public int Picture_Number { get; set; }
        public string Description { get; set; }
        public byte[] Mini_Version { get; set; }
        public byte[] Full_Version { get; set; }
    }
}
